### ISSUE TITLE
Error, After Opening in existing browser session.

### ISSUE THREAD

**Issue by Ikhari** [LeagueOfPoro/EpicRPGCaptcha#1]
2022-07-28 17:12:39.927837: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2022-07-28 17:12:42.689724: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-07-28 17:12:42.691142: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2022-07-28 17:12:42.710206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3060 Laptop GPU computeCapability: 8.6
coreClock: 1.425GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2022-07-28 17:12:42.710611: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2022-07-28 17:12:42.720544: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2022-07-28 17:12:42.720774: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2022-07-28 17:12:42.729048: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2022-07-28 17:12:42.730678: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2022-07-28 17:12:42.732260: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2022-07-28 17:12:42.736318: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2022-07-28 17:12:42.737655: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2022-07-28 17:12:42.737802: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-07-28 17:12:42.738816: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-28 17:12:42.739966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-07-28 17:12:42.740148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]
2022-07-28 17:12:42.740650: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Opening in existing browser session.
Traceback (most recent call last):
  File ".\main.py", line 96, in <module>
    driver = webdriver.Chrome(options=options)
  File "C:\Users\Ikhari\.virtualenvs\EpicRPGCaptcha-qIN6lYfl\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "C:\Users\Ikhari\.virtualenvs\EpicRPGCaptcha-qIN6lYfl\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 98, in __init__
    options=options)
  File "C:\Users\Ikhari\.virtualenvs\EpicRPGCaptcha-qIN6lYfl\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Ikhari\.virtualenvs\EpicRPGCaptcha-qIN6lYfl\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Ikhari\.virtualenvs\EpicRPGCaptcha-qIN6lYfl\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Ikhari\.virtualenvs\EpicRPGCaptcha-qIN6lYfl\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
Stacktrace:
Backtrace:
        Ordinal0 [0x00A95FD3+2187219]
        Ordinal0 [0x00A2E6D1+1763025]
        Ordinal0 [0x00943E78+802424]
        Ordinal0 [0x00961F32+925490]
        Ordinal0 [0x0095E691+910993]
        Ordinal0 [0x009917F0+1120240]
        Ordinal0 [0x0099144A+1119306]
        Ordinal0 [0x0098C9A6+1100198]
        Ordinal0 [0x00966F80+946048]
        Ordinal0 [0x00967E76+949878]
        GetHandleVerifier [0x00D390C2+2721218]
        GetHandleVerifier [0x00D2AAF0+2662384]
        GetHandleVerifier [0x00B2137A+526458]
        GetHandleVerifier [0x00B20416+522518]
        Ordinal0 [0x00A34EAB+1789611]
        Ordinal0 [0x00A397A8+1808296]
        Ordinal0 [0x00A39895+1808533]
        Ordinal0 [0x00A426C1+1844929]
        BaseThreadInitThunk [0x76536739+25]
        RtlGetFullPathName_UEx [0x76FE8FEF+1215]
        RtlGetFullPathName_UEx [0x76FE8FBD+1165]

**Comment by groundhogday-destroyerofworlds** [comment]
Did you ever find the fix
